### ISSUE TITLE
create-react-app 2.0 + babel 7 issues

### ISSUE THREAD

**Issue by cgestes** [quentinvernot/dumb-reducer#3]
Hi,

I get the following error when building using create-react-app version 2 (branch: next). 
PS: v2 of create-react-app depends on babel 7.

```
./node_modules/dumb-reducer/es/index.js
Syntax error: /home/ctaf/src/lana-notes/node_modules/dumb-reducer/es/index.js: Support for the experimental syntax 'objectRestSpread' isn't currently enabled (6:50):

  4 | 
  5 | function makeDumbReducer(prefix, initialState = {}, specialReducers = {}) {
> 6 |   return function (state = initialState, { type, ...payload } = {}) {
    |                                                  ^
  7 |     if (type) {
  8 |       if (specialReducers[type]) {
  9 |         return specialReducers[type](state, payload);

Add @babel/plugin-proposal-object-rest-spread (https://git.io/vb4Ss) to the 'plugins' section of your Babel config to enable transformation.
```
Any idea where the issue comes from?

**Comment by quentinvernot** [comment]
Right... so... it should have fixed itself. Babel used not to understand the rest/spread syntax by default (it needed a syntax plugin to do that), it does since the release of babel 7 ([august 2018](https://github.com/babel/babel/releases/tag/v7.0.0)).

`create-react-app` did the upgrade long ago, everything should be fine now. Close?

**Comment by cgestes** [comment]
Yeah it is fixed :)
